# Generated by Django 2.1.1 on 2020-01-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='task',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
