# Generated by Django 2.1.1 on 2020-01-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200107_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='task',
        ),
    ]
