# Generated by Django 2.1.1 on 2020-01-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_folder_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
